### ISSUE TITLE
Add to account right click link -> crash

### ISSUE THREAD

**Issue by liamdawe** [desura/desura-app#969]
I had TRI listed in my Play menu. I right clicked and noticed a "Add to account" option, clicked it, game vanish and crash.

/home/liam/Downloads/desura/lib/lib/lib/lib/lib/desura: line 21:  5140 Segmentation fault      $DESURA_DEBUGGERS $DIR/lib/desura $@

Crash log is empty.

Loaded again, decided to install it this time. Crash again.

/devroot/teamcity/buildAgent/work/2d0cde112ff3bd73/src/include/SharedObjectLoader.h:119 - Error getting function CEF_SetApiVersion: '(null)'
/home/liam/Downloads/desura/lib/lib/lib/lib/lib/desura: line 21:  5405 Segmentation fault      $DESURA_DEBUGGERS $DIR/lib/desura $@

**Comment by TheBeastie** [comment]
Fixed with stability fixes earlier.  Unable to replicate currently.  Closing.

**Comment by liamdawe** [comment]
When will it be live in the client download to re-test?

**Comment by codethulu** [comment]
We are unable to reproduce it in the current live client.

**Comment by liamdawe** [comment]
Still happens for me, just checked.

This happens on TRI, not sure why it's in my list with an "Add to account" button.

liam@liam-desktop ~ $ '/home/liam/Downloads/desura/desura' 
$XDG_CONFIG_HOME not set, falling back to $HOME/.config.$XDG_CACHE_HOME not set, falling back to $HOME/.cache.Saving crash report to: /home/liam/.desura/crash_log.txt
/devroot/teamcity/buildAgent/work/2d0cde112ff3bd73/src/include/SharedObjectLoader.h:119 - Error getting function CEF_SetApiVersion: '(null)'

Crash log is empty.

**Comment by TheBeastie** [comment]
Thank you Liam.
Which game were you right clicking on to add?  Or is this still TRI?

**Comment by liamdawe** [comment]
This is still TRI, it's the only game I have this random add to account option on.

**Comment by codethulu** [comment]
I see the option for "Add to Account" on TRI and OpenRA. While it isn't clear that selecting it does anything (presumably after you add something to your account, you would be able to remove it instead of continuing to add it), it does not crash.

I notice that you have nested lib/'s; can you try a fresh install of the client in case you're picking up some bad behavior that wasn't removed?

**Comment by liamdawe** [comment]
Same error on a fresh install.

The Add to account option doesn't make all that much sense anyway, since it's obviously on my account or I wouldn't see it in my list.

I can even install it bypassing the api errors and going to version -> pre-order, and it installs and runs.
